files:
  - filename: xsus
    url: http://106.75.143.245:3390/api/v1/client/subscribe?token=46df0e5a0b59a78ab3102339d9245f24
    download_location: ./downloads/
  # - filename: example2.pdf
  #   url: https://www.example.com/files/example2.pdf
  #   download_location: ./documents/
  # - filename: example3.zip
  #   url: https://www.example.com/files/example3.zip
  #   download_location: ./

folders: #  配置多个文件夹批量备份 (来自不同仓库)
  - github_repo: ACL4SSR/ACL4SSR  #  第一个文件夹来自 ACL4SSR/ACL4SSR 仓库
    branch: master
    folder_path: Clash/Ruleset
    file_extension: .list
    backup_location: ./config/Ruleset/
