files:
  - filename: xsus
    url: http://106.75.143.245:3390/api/v1/client/subscribe?token=46df0e5a0b59a78ab3102339d9245f24
    download_location: ./downloads/
  - filename: AdvertisingLite.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: Hijacking.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hijacking/Hijacking.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: OpenAI.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: Gemini.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: Claude.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: Copilot.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: Apple.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: Bahamut.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: BiliBili.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: Game.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: Microsoft.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: MicrosoftEdge.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/MicrosoftEdge/MicrosoftEdge.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: OneDrive.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: GoogleFCM.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: Direct.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: China.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: ChinaIPs_IP.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPs/ChinaIPs_IP.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: GovCN.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GovCN/GovCN.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: PrivateTracker.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: CloudCN.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Cloud/CloudCN/CloudCN.list
    download_location: ./config/Ruleset/blackmatrix7/
  
  - filename: Lan.list
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list
    download_location: ./config/Ruleset/blackmatrix7/


folders:
  - github_repo: ACL4SSR/ACL4SSR
    branch: master
    folder_path: Clash
    file_extension: .*
    backup_location: ./config/Ruleset/ACL4SSR/
    recursive: true
